### PR TITLE
Option to customize deploy branch

### PR DESCRIPTION
**Pull request by julienma**
2 fixes here:
- push `$GITHUB_SHA` instead of `HEAD`. [`GITHUB_SHA`](help.github.com/en/actions/reference/events-that-trigger-workflows#push-event-push) refers to the actual commit being pushed when workflow is triggered, whereas the `HEAD` reference could move if multiple commits are pushed in rapid succession, resulting in a "wrong" commit being deployed.
- allow dokku to deploy to any branch, even when deploy branch is different than `master`, see http://dokku.viewdocs.io/dokku/deployment/methods/git/#changing-the-deploy-branch.

---

Also, I didn't add this to the PR because not sure if you want to reference other actions or not, but I think this would be a nice addition to the README (and it's zero-config).

Basically, there's [this GH Action](https://github.com/marketplace/actions/cancel-workflow-action) which cancels queued or in progress workflows whenever they're outdated. This could happen if a commit is pushed while a build is already ongoing. Instead of waiting for the current build to finish (which would already be outdated), it is canceled so the new build is processed immediately.

Let me know if you're ok I add this:

```diff
name: 'Deploy to my Dokku instance'

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
+    - name: Cancel Previous Runs
+      uses: styfle/cancel-workflow-action@0.4.0
+      with:
+        access_token: ${{ github.token }}
    
    - name: Cloning repo # This step is required
      uses: actions/checkout@v2

    # This step is required or you might get an error from Dokku
    - run: git fetch --prune --unshallow 
  
    - name: Push to dokku
      uses: obrassard/action-dokku-deploy@v1.0.0
      with:
       dokku_repo: 'ssh://dokku@dokku.myhost.ca:22/appname'
       ssh_key: ${{ secrets.SSH_KEY }}
       deploy_branch: 'develop'
```

### CODE REVIEW

**Review by obrassard — APPROVED** [review]

**Comment by obrassard** [comment]
The proposed changes looks good to me !! 
For `cancel-workflow-action`, have you already tested it with dokku? I just want to confirm that it won't cause any problems if the build is interrupted on the dokku server.

**Comment by julienma** [comment]
I did got an issue once, related to Dokku "locking" an app while it's being deployed.

I think what happened was that the build got started on Dokku, and then because the GHAction got canceled, the deploy lock never got removed.

I'm wondering if we could systematically unlock the deploy whenever the workflow runs?
See http://dokku.viewdocs.io/dokku/deployment/application-management/#unlocking-app-deploys

But then maybe this is too far out of the scope of this action, and you might not want to care about this. Still, I'm wondering... :)
Anyway, this is unrelated to this PR, and if you want to continue the discussion we could move it to another issue?

**Comment by obrassard** [comment]
Indeed, I'll merge this PR and open another issue for that

**Comment by julienma** [comment]
👍 
You might want to create a new tag ;)

**Comment by obrassard** [comment]
Sure I will, I am just waiting to see what we'll do with issue #5 (if we implement something for it I will create a release combining both changes)

**Pull request merged**
